Interfaces:
    # Ensure that all settings in this file are consistent with the settings in the instrument's LIS configuration.
    Serial:
        # The ReceiverId should match the "Sender ID" field on the instrument's LIS configuration screen.
      - ReceiverId:    IMMULITE
        # The password can be empty, but it should always match the password field on the instrument's LIS configuration screen.
        Password:
        # Provide the serial port connected to the instrument.
        Portname:   COM2
        # Acceptable baud rate values include 1200, 2400, 4800, or 9600 (default). Some systems may also support 19200 or 38400.
        Baud:   9600 
        # Acceptable parity values include None (default), Even, or Odd.
        Parity: None
        # Data bits may be 5, 6, 7, or 8 (default).
        Databits:   8
        # Stop bits may be One (default), OnePointFive, or Two.
        Stopbits:   One
        # Handshake protocols are not included in the specification. Only the default value of None is recommended.
        Handshake:  None
        # UseLegacyFrameSize determines how long a single message frame can be -- anything longer will be split into intermediate frames. 
        # Set to true to use ASTM-1394 limit of 240 characters. Set to false to use CLSI-LIS2-A2 limit of 63,993 characters.
        UseLegacyFrameSize:  true
        # AutoSendOrders is the interval in milliseconds for checking the database for new order request messages to send.
        # A value of 0 disables automatically sending orders, and they will only be sent in response to a query message from the instrument.
        AutoSendOrders:   0

      ## Uncomment the following lines to add additional instruments with serial port connections.
      #- ReceiverId:    INSTRUMENT_NAME
      #  password:
      #  portname:   COM#
      #  baud:   19200
      #  parity: None
      #  databits:   8
      #  stopbits:   One
      #  handshake:  None
      #  UseLegacyFrameSize:  false
      #  AutoSendOrders:    false

    Tcp:
      - ReceiverId:
        Password:
        UseLegacyFrameSize:
        Socket:
        AutoSendOrders:   0
 
ServiceConfig:
    UseExternalDb:    false
    ConnectionString:  
    DbPollInterval:
    ListenHl7:     true
    Hl7TcpPort:   1394
    LisId: UniversaLIS
    Address:
    Phone:

TableFieldMappings:
    PatientRecord:
        PAPID: 
        LAPID: 
        PID3: 
        PName: 
        MMName: 
        DOB: 
        PSex: 
        PRace: 
        PAddr: 
        Reserved: 
        PTelNo: 
        Attending: 
        Special1: 
        Special2: 
        PHeight: 
        PWeight: 
        PDiag: 
        PMeds: 
        PDiet: 
        PF1: 
        PF2: 
        AdmDates: 
        AdmStatus: 
        PLocation: 
        AltCodeNature: 
        AltCode: 
        PReligion: 
        PMarStatus: 
        PIsoStatus: 
        PLanguage: 
        HospService: 
        HospInst: 
        DoseCat: 
    
    OrderRecord:
        PRID: 
        SpecID: 
        InSpecID: 
        UTID: 
        OrderDate: 
        CollectDate: 
        CollEndTime: 
        CollVolume: 
        Collector: 
        ActCode: 
        DangerCode: 
        RelClinInfo: 
        SpecRecd: 
        SpecDesc: 
        OrdPhys: 
        PhysTelNo: 
        UF1: 
        UF2: 
        LF1: 
        LF2: 
        LastReported: 
        BillRef: 
        InSectID: 
        RepType: 
        Reserved: 
        SpecColLocation: 
        NosInfFlag: 
        SpecService: 
        SpecInst: 
    
    ResultRecord:
        ORID: 
        UTID: 
        Result: 
        Unit: 
        RefRange: 
        Abnormal: 
        AbNature: 
        ResStatus: 
        NormsChanged: 
        OpID: 
        TestStart: 
        TestEnd: 
        InstID: 
    
    CommentRecord:
        Source: 
        Text: 
        Type: 
    
    QueryRecord:
        StartRange: 
        EndRange: 
        UTID: 
        ReqLimNature: 
        ReqResBeginDT: 
        ReqResEndDT: 
        ReqPhysName: 
        ReqPhysTelNo: 
        UF1: 
        UF2: 
        ReqInfoStatus: 
    
    ScientificRecord:
        AnalMeth: 
        Instrument: 
        Reagents: 
        Units: 
        QC: 
        SpecDesc: 
        Reserved: 
        Container: 
        SpecID: 
        Analyte: 
        Result: 
        ResUnits: 
        CollectDT: 
        ResultDT: 
        AnalPreSteps: 
        PatDiag: 
        PatDOB: 
        PSex: 
        PRace: 