interfaces:
  - receiver_id:    IMMULITE
    portname:   COM4
    baud:   9600
    parity: None
    databits:   8
    stopbits:   One
    handshake:  None
  - receiver_id:    CLINITEK
    portname:   COM5
    baud:   19200
    parity: None
    databits:   8
    stopbits:   One
    handshake:  None